### ISSUE TITLE
sql error with 2.1.9

### ISSUE THREAD

**Issue by MithrandirCraft** [DevLeoko/AdvancedBan#367]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.1.9-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Waterfall server + 4 Paper servers
 
_What server version (/version) are you using?_
git-Paper-350 (MC: 1.15.2)

_Please provide the EXACT steps required to reproduce the problem..._
May be specific to my server, but this was just an update from 2.1.7 to 2.1.9, with no other changes.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._
https://gist.github.com/MithrandirCraft/d78ea03783469c16b62d17101731687f

_Add any additional information below._
The error seems to be telling me to modify some timezone time value, which I'm looking into.
For now I had to disable the plugin.
No one can enter the server while this error is present. I'm asuming for configured security reasons.

**Comment by DevLeoko** [comment]
This seems to be an issue with your server configuration.

With the latest dev version, you can define custom MySQL properties. Adding a `&serverTimezone=UTC` should fix your issue.

Your MySQL>Properties should look like this: (config.yml)
```YAML
MySQL:
  IP: localhost
  DB-Name: database-name
  Username: admin
  Password: superSecret
  Port: 3306
  Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC'
```
