### ISSUE TITLE
Cannot connect to MySQL.

### ISSUE THREAD

**Issue by jonnytutorials** [DevLeoko/AdvancedBan#542]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan-Bundle-2.3.0-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot
 
_What server version (/version) are you using?_
1.16.5

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
(Error-Log from /plugins/AdvancedBan/logs/latest.log) https://pastebin.com/LuqBLiUm

_System-Details_
- Java 16.0.1
- MySQL 8.0.27-0ubuntu0.21.04.1

_config.yml MySQL Settings_
```
UseMySQL: true

MySQL:
  IP: localhost
  DB-Name: bansys
  Username: bansys
  Password: ***
  Port: 3306
  Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8'
```
